pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/lakshmi40/ci-demo.git'
            }
        }

        stage('Build') {
            steps {
                bat '''
                cd ci-demo-project
                mvn clean install
                '''
            }
        }

        stage('Test') {
            steps {
                bat '''
                cd ci-demo-project
                mvn test
                '''
            }
        }

        stage('Deploy') {
            steps {
                echo 'Build and Tests Successful - Ready to Deploy'
            }
        }
    }
}
